---

# Action to perform
#       values: provision, deprovision, purge
#   purge completely remove all files, configuration, docker images
action: provision

# Default network for pod
#       values: flannel
default_network: flannel

# CNI-multiplexer to use
#       values: multus
cni_multiplexer: multus

# CNI plugins supported
#  1. Kubevirt-ovs (https://github.com/kubevirt/ovs-cni)
#  2. Intel-sriov (https://github.com/intel/sriov-cni)
#  3. Intel-userspace (https://github.com/intel/userspace-cni-network-plugin)
#
# note: intel-sriov also deploys sriov-device-plugin (https://github.com/intel/sriov-network-device-plugin)
#


