---
- hosts: all
  vars_files:
    - config.yml
  roles:
    - {role: pre-deploy           }
    - {role: "{{default_network}}"}
    - {role: "{{cni_multiplexer}}"}
    - {role: kubevirt-ovs         }
    - {role: intel-sriov          }
    - {role: intel-userspace      }


